[package]
name = "astu-action"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
russh = "0.45"
socket2 = "0.5"
ssh-key = { version = "0.6.6", features = ["ed25519"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
rstest = "0.22"
