[package]
name = "kush"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.1", features = ["derive"] }
serde_derive = "1.0.163"
serde_json = "1.0.96"
skim = "0.10.4"
tracing = "0.1.37"
url = "2.4.0"
which = "4.4.0"
