[workspace]
members = [".", "kush-connect", "kush-uri"]

[package]
name = "kush"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.80"
clap = { version = "4.3.1", features = ["derive"] }
confy = { version = "0.5.1", default-features = false, features = ["yaml_conf"] }
hickory-resolver = "0.24.0"
regex = "1.8.4"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
skim = "0.10.4"
thiserror = "1.0.58"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.37"
url = "2.4.0"
which = "4.4.0"
xdg = "2.5.0"

[dev-dependencies]
rstest = "0.17.0"
serde_yaml = "0.9.21"
