[package]
name = "astu-resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
camino = "1.1.9"
fluent-uri = "0.2"
futures = "0.3"
hickory-resolver = "0.24"
ipnet = "2"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1.15", features = ["io-util"] }
tracing = "0.1"

[dev-dependencies]
rstest = "0.23"
