[package]
name = "astu-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1.82"
futures = "0.3"
socket2 = "0.5.7"
tokio = { version = "1.40.0", features = ["full"] }

[dev-dependencies]
rstest = "0.22"
