[package]
name = "astu-db"
version = "0.1.0"
edition = "2021"

[dependencies]
astu-action = { path = "../action" }
anyhow = "1"
async-trait = "0.1"
futures = "0.3"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "migrate", "derive"] }
tracing = "0.1"

[dev-dependencies]
rstest = "0.22"
tokio = { version = "1", features = ["full"] }
